language: cpp 
matrix:
  include:
     compiler: cpp
script:
  - cpp 2.cpp
  - echo $GITHUB_API_KEY
  - git clone https://github.com/maxim1436/doc.io.git
  - mv Doxyfile 2.cpp doc.io/
  - cd doc.io
  - rm Doxyfile 2.cpp
  - git config --global user.name "travis"
  - git config --global user.email "pivanov_m@mail.ru"
  - git add -A
  - git commit -am "Update doc from Travis CI"
  - git config --global push.default simple
  - git push -f -q https://maxim1436:${GITHUB_API_KEY}@github.com/maxim1436/doc.io.git
branches:
  only:
    - main
